sudo: true
language: haskell
cabal: "3.2"

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  # Cabal
  - ghc: 8.10.2
  - ghc: 8.10.1

install:
  - ghc --version
  - cabal --version
  - cabal new-update
  - cabal new-build

notifications:
  email: false